<script setup lang="ts">
import { computed, ref } from "vue";
import { useCharacterStore } from "../stores/characterStore";

const store = useCharacterStore();

// CLASS_SKILL_INDEX from C++: CLASS_SKILL_INDEX[saveFileIdx] = displayIdx
// We need the INVERSE: DISPLAY_TO_SAVE[displayIdx] = saveFileIdx
// Generated by inverting the C++ arrays

const DISPLAY_TO_SAVE_INDEX: Record<number, number[]> = {
  // Amazon: {0,1,10,11,20,2,3,12,21,22,4,13,14,23,24,5,6,15,25,26,7,8,16,17,27,9,18,19,28,29}
  0: [0,1,5,6,10,15,16,20,21,25,2,3,7,11,12,17,22,23,26,27,4,8,9,13,14,18,19,24,28,29],
  // Sorceress: {0,1,10,20,21,2,11,12,22,23,3,4,13,14,24,5,6,15,16,25,7,17,18,26,27,8,9,19,28,29}
  1: [0,1,5,10,11,15,16,20,25,26,2,6,7,12,13,17,18,21,22,27,3,4,8,9,14,19,23,24,28,29],
  // Necromancer: {0,10,11,20,21,1,2,12,13,22,3,4,14,23,24,5,6,15,16,25,7,8,17,26,27,9,18,19,28,29}
  2: [0,5,6,10,11,15,16,20,21,25,1,2,7,8,12,17,18,22,26,27,3,4,9,13,14,19,23,24,28,29],
  // Paladin: {0,1,10,20,21,2,11,12,22,23,3,4,13,24,25,5,6,14,15,26,7,8,16,17,27,9,18,19,28,29}
  3: [0,1,5,10,11,15,16,20,21,25,2,6,7,12,17,18,22,23,27,3,4,8,9,13,14,19,24,28,29,26],
  // Barbarian: {0,10,11,12,20,21,1,2,13,14,15,22,23,3,4,16,24,5,6,17,25,7,18,26,27,8,9,19,28,29}
  4: [0,6,7,12,13,17,18,21,25,26,1,2,3,8,9,10,15,19,20,27,4,5,11,14,22,23,16,24,28,29],
  // Druid: {0,1,10,11,20,2,3,12,21,22,4,13,14,23,24,5,6,15,16,25,7,17,18,26,27,8,9,19,28,29}
  5: [0,1,5,6,10,15,16,20,25,26,2,3,7,11,12,17,18,21,22,27,4,8,9,13,14,19,23,24,28,29],
  // Assassin: {0,10,11,20,21,1,2,12,22,23,3,4,13,14,24,5,15,16,25,26,6,7,17,27,28,8,9,18,19,29}
  6: [0,5,6,10,11,15,20,21,25,26,1,2,7,12,13,16,22,27,28,3,4,8,9,14,17,18,23,24,19,29]
};

// Skill trees for each class (3 trees × 10 skills each)
const skillTrees: Record<string, { name: string; skills: string[] }[]> = {
  Amazon: [
    {
      name: "Bow and Crossbow",
      skills: ["Magic Arrow", "Fire Arrow", "Cold Arrow", "Multiple Shot", "Exploding Arrow", "Ice Arrow", "Guided Arrow", "Strafe", "Immolation Arrow", "Freezing Arrow"]
    },
    {
      name: "Passive and Magic",
      skills: ["Inner Sight", "Critical Strike", "Dodge", "Slow Missiles", "Avoid", "Penetrate", "Dopplezon", "Evade", "Valkyrie", "Pierce"]
    },
    {
      name: "Javelin and Spear",
      skills: ["Jab", "Power Strike", "Poison Javelin", "Impale", "Lightning Bolt", "Charged Strike", "Plague Javelin", "Fend", "Lightning Strike", "Lightning Fury"]
    }
  ],
  Sorceress: [
    {
      name: "Fire Spells",
      skills: ["Fire Bolt", "Warmth", "Inferno", "Blaze", "Fire Ball", "Fire Wall", "Enchant", "Meteor", "Fire Mastery", "Hydra"]
    },
    {
      name: "Lightning Spells",
      skills: ["Charged Bolt", "Static Field", "Telekinesis", "Nova", "Lightning", "Chain Lightning", "Teleport", "Thunder Storm", "Energy Shield", "Lightning Mastery"]
    },
    {
      name: "Cold Spells",
      skills: ["Ice Bolt", "Frozen Armor", "Frost Nova", "Ice Blast", "Shiver Armor", "Glacial Spike", "Blizzard", "Chilling Armor", "Frozen Orb", "Cold Mastery"]
    }
  ],
  Necromancer: [
    {
      name: "Curses",
      skills: ["Amplify Damage", "Dim Vision", "Weaken", "Iron Maiden", "Terror", "Confuse", "Life Tap", "Attract", "Decrepify", "Lower Resist"]
    },
    {
      name: "Poison & Bone",
      skills: ["Teeth", "Bone Armor", "Poison Dagger", "Corpse Explosion", "Bone Wall", "Poison Explosion", "Bone Spear", "Bone Prison", "Poison Nova", "Bone Spirit"]
    },
    {
      name: "Summoning",
      skills: ["Skeleton Mastery", "Raise Skeleton", "Clay Golem", "Golem Mastery", "Raise Skeletal Mage", "Blood Golem", "Summon Resist", "Iron Golem", "Fire Golem", "Revive"]
    }
  ],
  Paladin: [
    {
      name: "Combat",
      skills: ["Sacrifice", "Smite", "Holy Bolt", "Zeal", "Charge", "Vengeance", "Blessed Hammer", "Conversion", "Holy Shield", "Fist of the Heavens"]
    },
    {
      name: "Offensive Auras",
      skills: ["Might", "Holy Fire", "Thorns", "Blessed Aim", "Concentration", "Holy Freeze", "Holy Shock", "Sanctuary", "Fanaticism", "Conviction"]
    },
    {
      name: "Defensive Auras",
      skills: ["Prayer", "Resist Fire", "Defiance", "Resist Cold", "Cleansing", "Resist Lightning", "Vigor", "Meditation", "Redemption", "Salvation"]
    }
  ],
  Barbarian: [
    {
      name: "Combat",
      skills: ["Bash", "Leap", "Double Swing", "Stun", "Double Throw", "Leap Attack", "Concentrate", "Frenzy", "Whirlwind", "Berserk"]
    },
    {
      name: "Masteries",
      skills: ["Sword Mastery", "Axe Mastery", "Mace Mastery", "Pole Arm Mastery", "Throwing Mastery", "Spear Mastery", "Increased Stamina", "Iron Skin", "Increased Speed", "Natural Resistance"]
    },
    {
      name: "Warcries",
      skills: ["Howl", "Find Potion", "Taunt", "Shout", "Find Item", "Battle Cry", "Battle Orders", "Grim Ward", "War Cry", "Battle Command"]
    }
  ],
  Druid: [
    {
      name: "Summoning",
      skills: ["Raven", "Poison Creeper", "Oak Sage", "Summon Spirit Wolf", "Carrion Vine", "Heart of Wolverine", "Summon Fenris", "Solar Creeper", "Spirit of Barbs", "Summon Grizzly"]
    },
    {
      name: "Shape Shifting",
      skills: ["Werewolf", "Lycanthropy", "Werebear", "Feral Rage", "Maul", "Rabies", "Fire Claws", "Hunger", "Shock Wave", "Fury"]
    },
    {
      name: "Elemental",
      skills: ["Firestorm", "Molten Boulder", "Arctic Blast", "Fissure", "Cyclone Armor", "Twister", "Volcano", "Tornado", "Armageddon", "Hurricane"]
    }
  ],
  Assassin: [
    {
      name: "Traps",
      skills: ["Fire Blast", "Shock Web", "Blade Sentinel", "Charged Bolt Sentry", "Wake of Fire", "Blade Fury", "Lightning Sentry", "Inferno Sentry", "Death Sentry", "Blade Shield"]
    },
    {
      name: "Shadow Disciplines",
      skills: ["Claw Mastery", "Psychic Hammer", "Burst of Speed", "Weapon Block", "Cloak of Shadows", "Fade", "Shadow Warrior", "Mind Blast", "Venom", "Shadow Master"]
    },
    {
      name: "Martial Arts",
      skills: ["Tiger Strike", "Dragon Talon", "Fists of Fire", "Dragon Claw", "Cobra Strike", "Claws of Thunder", "Dragon Tail", "Blades of Ice", "Dragon Flight", "Phoenix Strike"]
    }
  ]
};

// Use store's charClass directly (returns "Amazon", "Sorceress", etc.)
// For class index, access saveData
const classIndex = computed(() => {
  return store.saveData?.header?.char_class ?? -1;
});

const skillLevels = computed(() => {
  if (!store.saveData?.skills?.skills) return [];
  return store.saveData.skills.skills;
});

const currentSkillTrees = computed(() => {
  if (!store.charClass || store.charClass === "Unknown") return [];
  return skillTrees[store.charClass] || [];
});

const totalPoints = computed(() => {
  if (!store.saveData?.skills?.skills) return 0;
  return store.saveData.skills.skills.reduce((sum: number, level: number) => sum + level, 0);
});

// Get save file index for a skill at given display position (tree + position in tree)
const getSkillIndex = (treeIndex: number, skillInTreeIndex: number): number => {
  const clsIdx = classIndex.value;
  if (clsIdx < 0 || clsIdx > 6) return -1;

  const displayIndex = treeIndex * 10 + skillInTreeIndex;
  const mapping = DISPLAY_TO_SAVE_INDEX[clsIdx];
  return mapping ? mapping[displayIndex] : displayIndex;
};

// Get skill level from save data
const getSkillLevel = (treeIndex: number, skillInTreeIndex: number): number => {
  const saveIndex = getSkillIndex(treeIndex, skillInTreeIndex);
  if (saveIndex < 0 || saveIndex >= skillLevels.value.length) return 0;
  return skillLevels.value[saveIndex];
};

// Set skill level in save data (with proper reactivity)
const setSkillLevel = (treeIndex: number, skillInTreeIndex: number, level: number) => {
  const saveIndex = getSkillIndex(treeIndex, skillInTreeIndex);
  if (saveIndex < 0 || !store.saveData?.skills) return;

  // Clamp level to valid range (0-127)
  const clampedLevel = Math.max(0, Math.min(127, level));

  // Create new array to trigger Vue reactivity
  const newSkills = [...store.saveData.skills.skills];
  newSkills[saveIndex] = clampedLevel;
  store.saveData.skills.skills = newSkills;
  store.setModified(true);
};

// Increment skill level
const incrementSkill = (treeIndex: number, skillInTreeIndex: number) => {
  const current = getSkillLevel(treeIndex, skillInTreeIndex);
  if (current < 127) {
    setSkillLevel(treeIndex, skillInTreeIndex, current + 1);
  }
};

// Decrement skill level
const decrementSkill = (treeIndex: number, skillInTreeIndex: number) => {
  const current = getSkillLevel(treeIndex, skillInTreeIndex);
  if (current > 0) {
    setSkillLevel(treeIndex, skillInTreeIndex, current - 1);
  }
};

// Handle direct input change
const onInputChange = (treeIndex: number, skillInTreeIndex: number, event: Event) => {
  const target = event.target as HTMLInputElement;
  const value = parseInt(target.value) || 0;
  setSkillLevel(treeIndex, skillInTreeIndex, value);
};

// Set skill level by raw index (for fallback view)
const setRawSkillLevel = (index: number, level: number) => {
  if (!store.saveData?.skills || index < 0 || index >= 30) return;
  const clampedLevel = Math.max(0, Math.min(127, level));
  const newSkills = [...store.saveData.skills.skills];
  newSkills[index] = clampedLevel;
  store.saveData.skills.skills = newSkills;
  store.setModified(true);
};

// Set all skills to a specific level
const setAllSkillLevel = ref<number>(0);
const applyAllSkills = () => {
  if (!store.saveData?.skills) return;
  const level = Math.max(0, Math.min(127, setAllSkillLevel.value));
  const newSkills = Array(30).fill(level) as number[];
  store.saveData.skills.skills = newSkills;
  store.setModified(true);
};

// Max all skills
const maxAllSkills = () => {
  if (!store.saveData?.skills) return;
  const newSkills = Array(30).fill(20) as number[];
  store.saveData.skills.skills = newSkills;
  store.setModified(true);
};

// Reset all skills to 0
const resetAllSkills = () => {
  if (!store.saveData?.skills) return;
  const newSkills = Array(30).fill(0) as number[];
  store.saveData.skills.skills = newSkills;
  store.setModified(true);
};
</script>

<template>
  <div class="view-container">
    <h2>Skills</h2>

    <div v-if="store.saveData" class="skills-content">
      <!-- Class Header -->
      <div class="class-header">
        <span class="class-name">{{ store.charClass }}</span>
        <span class="points-summary">Total Points: {{ totalPoints }}</span>
      </div>

      <!-- Bulk Actions -->
      <div class="bulk-actions">
        <label>
          Set all:
          <input
            type="number"
            v-model.number="setAllSkillLevel"
            min="0"
            max="127"
            class="level-input"
          />
        </label>
        <button @click="applyAllSkills" class="action-btn">Apply</button>
        <button @click="maxAllSkills" class="action-btn">Max All (20)</button>
        <button @click="resetAllSkills" class="action-btn danger">Reset All</button>
      </div>

      <!-- Skill Trees -->
      <div v-if="currentSkillTrees.length" class="skill-trees">
        <div
          v-for="(tree, treeIdx) in currentSkillTrees"
          :key="treeIdx"
          class="skill-tree"
        >
          <h3 class="tree-name">{{ tree.name }}</h3>
          <div class="skill-list">
            <div
              v-for="(skill, skillIdx) in tree.skills"
              :key="skillIdx"
              class="skill-item"
              :class="{ 'has-points': getSkillLevel(treeIdx, skillIdx) > 0 }"
            >
              <span class="skill-name">{{ skill }}</span>
              <div class="skill-controls">
                <button
                  class="skill-btn"
                  @click="decrementSkill(treeIdx, skillIdx)"
                  :disabled="getSkillLevel(treeIdx, skillIdx) <= 0"
                >−</button>
                <input
                  type="number"
                  :value="getSkillLevel(treeIdx, skillIdx)"
                  @input="onInputChange(treeIdx, skillIdx, $event)"
                  min="0"
                  max="127"
                  class="skill-level-input"
                />
                <button
                  class="skill-btn"
                  @click="incrementSkill(treeIdx, skillIdx)"
                  :disabled="getSkillLevel(treeIdx, skillIdx) >= 127"
                >+</button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Fallback for unknown classes - with edit controls -->
      <div v-else class="raw-skills">
        <p class="debug-info">Class index: {{ classIndex }}, charClass: "{{ store.charClass }}"</p>
        <div class="skills-list-fallback">
          <div v-for="(level, idx) in skillLevels" :key="idx" class="skill-item">
            <span class="skill-name">Skill {{ idx }}</span>
            <div class="skill-controls">
              <button
                class="skill-btn"
                @click="setRawSkillLevel(idx, level - 1)"
                :disabled="level <= 0"
              >−</button>
              <input
                type="number"
                :value="level"
                @input="setRawSkillLevel(idx, parseInt(($event.target as HTMLInputElement).value) || 0)"
                min="0"
                max="127"
                class="skill-level-input"
              />
              <button
                class="skill-btn"
                @click="setRawSkillLevel(idx, level + 1)"
                :disabled="level >= 127"
              >+</button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <p v-else>No data loaded.</p>
  </div>
</template>

<style scoped>
.view-container {
  padding: 1rem;
}

.skills-content {
  max-width: 1000px;
  margin: 0 auto;
}

.class-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1rem;
  padding-bottom: 0.75rem;
  border-bottom: 1px solid var(--border-gold);
}

.class-name {
  font-size: 1.25rem;
  font-weight: bold;
  color: var(--gold-primary);
}

.points-summary {
  font-size: 0.9rem;
  color: var(--text-secondary);
}

.bulk-actions {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  margin-bottom: 1.5rem;
  padding: 0.75rem;
  background: var(--bg-panel);
  border: 1px solid var(--border-dark);
  border-radius: 4px;
}

.bulk-actions label {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  color: var(--text-secondary);
  font-size: 0.85rem;
}

.level-input {
  width: 50px;
  padding: 4px 6px;
  background: var(--bg-cell);
  border: 1px solid var(--border-dark);
  color: var(--text-primary);
  border-radius: 3px;
  text-align: center;
  font-size: 0.85rem;
}

.level-input:focus {
  outline: none;
  border-color: var(--gold-dim);
}

.action-btn {
  padding: 4px 12px;
  font-size: 0.75rem;
  background: linear-gradient(180deg, #3a3a30 0%, #2a2a20 100%);
  border: 1px solid var(--border-light);
  color: var(--text-primary);
  border-radius: 3px;
  cursor: pointer;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.action-btn:hover {
  background: linear-gradient(180deg, #4a4a40 0%, #3a3a30 100%);
  border-color: var(--gold-dim);
  color: var(--gold-bright);
}

.action-btn.danger {
  border-color: var(--accent-red);
}

.action-btn.danger:hover {
  background: linear-gradient(180deg, #4a3030 0%, #3a2020 100%);
  border-color: #aa4040;
  color: #ff6666;
}

.skill-trees {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 1rem;
}

@media (max-width: 800px) {
  .skill-trees {
    grid-template-columns: repeat(2, 1fr);
  }
}

@media (max-width: 550px) {
  .skill-trees {
    grid-template-columns: 1fr;
  }
}

.skill-tree {
  background: var(--bg-panel);
  border: 1px solid var(--border-dark);
  border-radius: 4px;
  padding: 0.75rem;
}

.tree-name {
  margin: 0 0 0.5rem 0;
  font-size: 0.85rem;
  color: var(--gold-primary);
  text-transform: uppercase;
  letter-spacing: 0.05em;
  border-bottom: 1px solid var(--border-dark);
  padding-bottom: 0.4rem;
}

.skill-list {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}

.skill-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0.3rem 0.5rem;
  background: var(--bg-cell);
  border-radius: 3px;
  transition: background 0.15s;
}

.skill-item:hover {
  background: #1a1a14;
}

.skill-item.has-points {
  background: #1a2a1a;
  border-left: 2px solid var(--accent-green);
}

.skill-item.has-points .skill-name {
  color: var(--text-primary);
}

.skill-name {
  font-size: 0.8rem;
  color: var(--text-secondary);
  flex: 1;
}

.skill-controls {
  display: flex;
  align-items: center;
  gap: 0.25rem;
}

.skill-btn {
  width: 22px;
  height: 22px;
  padding: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  background: var(--bg-dark);
  border: 1px solid var(--border-dark);
  color: var(--text-secondary);
  border-radius: 3px;
  cursor: pointer;
  font-size: 0.9rem;
  font-weight: bold;
  transition: all 0.15s;
}

.skill-btn:hover:not(:disabled) {
  background: var(--bg-panel);
  border-color: var(--gold-dim);
  color: var(--gold-primary);
}

.skill-btn:disabled {
  opacity: 0.3;
  cursor: not-allowed;
}

.skill-level-input {
  width: 36px;
  padding: 2px 4px;
  background: var(--bg-cell);
  border: 1px solid var(--border-dark);
  color: var(--text-primary);
  border-radius: 3px;
  text-align: center;
  font-size: 0.85rem;
  font-weight: bold;
}

.skill-level-input:focus {
  outline: none;
  border-color: var(--gold-dim);
}

/* Hide number input spinners */
.skill-level-input::-webkit-outer-spin-button,
.skill-level-input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

.skill-level-input[type=number] {
  -moz-appearance: textfield;
}

.raw-skills {
  margin-top: 1rem;
}

.debug-info {
  color: var(--accent-red);
  margin-bottom: 1rem;
  font-size: 0.85rem;
  padding: 0.5rem;
  background: rgba(255, 100, 100, 0.1);
  border-radius: 4px;
}

.skills-list-fallback {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
  gap: 0.5rem;
}

.skills-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(100px, 1fr));
  gap: 0.5rem;
}
</style>
