// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CorpseData } from "./CorpseData";

export type Corpse = { magic: number, count: number, corpses: Array<CorpseData>, };
