// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemData } from "./ItemData";

export type D2Item = { data: ItemData, socketed_items: Array<D2Item>, };
