// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DifficultyWaypoints = { unknown: [number, number], waypoints: [number, number, number, number, number, number, number, number, number], unknown2: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], };
