// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { D2Item } from "./D2Item";

export type ItemList = { magic: number, items: Array<D2Item>, };
