// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WaypointData } from "./WaypointData";

export type Waypoints = { magic: number, unk1: number, size: number, modes: [WaypointData, WaypointData, WaypointData], };
