// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemList } from "./ItemList";

export type CorpseData = { unknown: number[], items: ItemList, };
