// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharSkills } from "./CharSkills";
import type { Corpse } from "./Corpse";
import type { D2sHeader } from "./D2sHeader";
import type { Golem } from "./Golem";
import type { ItemList } from "./ItemList";
import type { Mercenary } from "./Mercenary";
import type { PlayerStats } from "./PlayerStats";
import type { QuestInfo } from "./QuestInfo";
import type { Waypoints } from "./Waypoints";

export type D2sSave = { header: D2sHeader, quests: QuestInfo, waypoints: Waypoints, npc_data: number[], stats: PlayerStats, skills: CharSkills, items: ItemList, corpse: Corpse, mercenary: Mercenary, golem: Golem, };
