// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ItemData = { identified: boolean, socketed: boolean, ethereal: boolean, personalized: boolean, runeword: boolean, simple: boolean, location: number, position: number, column: number, row: number, container: number, type_id: number[], is_ear: boolean, width: number, height: number, };
