// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuestInfoData } from "./QuestInfoData";

export type QuestInfo = { magic: number, acts: number, size: number, modes: [QuestInfoData, QuestInfoData, QuestInfoData], };
