// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DifficultyWaypoints } from "./DifficultyWaypoints";

export type Waypoints = { magic: number, unknown: number, size: number, difficulties: [DifficultyWaypoints, DifficultyWaypoints, DifficultyWaypoints], };
